README.md
applications/jupyterlab-extension/package.json
applications/jupyterlab-extension/src/jupyter/kernelContext.ts
applications/standalone/package.json
applications/standalone/src/mock/context.ts
packages/client-core/src/common/ModuleFactory.tsx
packages/client-core/src/common/modelContext.ts
packages/client-core/src/common/modules.ts
packages/client-core/src/index.ts
packages/modules/README.md
packages/modules/package.json
packages/modules/src/Default.tsx
packages/modules/src/index.ts
packages/modules/tsconfig.json
packages/toy-vre/src/components/WorkflowPreview.tsx

Bootstrapped `modules` project with a default module panel view when no particular one was provided.

Added `modules` package

---

applications/jupyter-app/README.md
applications/jupyter-app/electron/src/index.html
applications/jupyter-app/electron/src/main.ts
applications/jupyter-app/electron/src/networkUtils.ts
applications/jupyter-app/electron/src/preload.ts
applications/jupyter-app/electron/tsconfig.json
applications/jupyter-app/main.py
applications/jupyter-app/package.json
applications/jupyter-app/src/index.ts
applications/jupyter-app/src/pageConfig.ts
applications/jupyter-app/webpack.config.js
tsconfig.json
yarn.lock

This PR includes a working app, but does not include packaging yet.

Running VRE as a desktop electron app

---

packages/client-ui/src/components/common/TopPageLayout.styles.ts
packages/client-ui/src/components/common/navigation/NavGroup.styles.ts
packages/client-ui/src/components/common/navigation/NavGroup.tsx
packages/client-ui/src/components/common/navigation/SideBar.styles.ts

CSS style fix:
* correct NavGroup styling
* make SideBar fixed
*make page content vertically scrollable

Style fix: NavGroup, SideBar, page content

---

applications/standalone/src/index.tsx
packages/client-ui/package.json
packages/client-ui/src/components/App.tsx
packages/client-ui/src/components/pages/IntroPage.styles.ts
packages/client-ui/src/components/pages/IntroPage.tsx
packages/client-ui/src/components/sample/PopularityChart.tsx
packages/client-ui/src/components/sample/PopularityChart.utils.ts
packages/client-ui/src/components/sample/Summary.tsx
packages/client-ui/src/components/sample/UserList.tsx
packages/client-ui/src/const/routes.tsx
packages/client-ui/src/types/types.d.ts
packages/client-ui/src/utils/date.ts
yarn.lock

Some dummy content to work with for now.

Create Intro page with dummy content

---

packages/client-ui/src/components/common/ProjectProgressBar.tsx
packages/client-ui/src/components/common/TopPageLayout.tsx
packages/client-ui/src/components/common/navigation/NavHeading.styles.ts
packages/client-ui/src/components/common/navigation/NavHeading.tsx
packages/client-ui/src/components/common/navigation/NavItem.tsx
packages/client-ui/src/components/common/navigation/NavProjectLink.styles.ts
packages/client-ui/src/components/common/navigation/NavProjectLink.tsx
packages/client-ui/src/components/common/navigation/SideBar.styles.ts
packages/client-ui/src/components/common/navigation/SideBar.tsx
packages/client-ui/src/const/routes.tsx
packages/client-ui/src/context/themeContext.tsx
packages/client-ui/src/types/types.d.ts

* Navigation items for on-going workflow projects
* Logo placeholder
* Several minor style tweaks across app

Project links on side bar + logo + style tweaks

---

packages/client-ui/src/components/pages/ToyVrePage.styles.ts
packages/client-ui/src/components/pages/ToyVrePage.tsx
packages/toy-vre/package.json
packages/toy-vre/src/components/App.tsx
packages/toy-vre/src/components/StatusView.tsx
packages/toy-vre/src/components/WorkflowPreview.tsx

Some toy VRE styling

---

applications/jupyter-app/babel.config.js
applications/jupyter-app/package.json
applications/jupyterlab-extension/babel.config.js
applications/jupyterlab-extension/package.json
applications/standalone/babel.config.js
applications/standalone/package.json
packages/datavis-components/package.json
packages/datavis-components/src/components/network-force.ts
packages/datavis-components/src/index.ts
packages/datavis-components/tsconfig.json
packages/modules/tsconfig.json
tsconfig.json
yarn.lock

Moved network graph from `web-components` into monorepo to make development easier.

Data visualisation components package

---

packages/modules/src/networkAnalysisDataMapping/index.tsx
packages/modules/src/networkAnalysisDataVis/index.tsx
yarn.lock

Extra calculated column indicating whether the node is isolated or not. It's taken into account before passing nodes to the graph.

Filter out isolated nodes in the backend

---

packages/datavis-components/src/components/network-force.ts
packages/modules/src/networkAnalysisDataVis/index.tsx

An optional flag indicating whether simulation should be reapplied on update.

Reapply simulation on update

---

backend/jupyter-middleware/dharpa/vre/context/kiara/app_context.py
backend/jupyter-middleware/dharpa/vre/dev/data_registry/mock.py
backend/jupyter-middleware/dharpa/vre/dev/modules/network_analysis.py
backend/jupyter-middleware/dharpa/vre/jupyter/controller.py
backend/jupyter-middleware/dharpa/vre/jupyter/message_handlers/module_io.py
backend/jupyter-middleware/setup.py
packages/jupyter-support/src/readinessProbe.ts
packages/modules/src/networkAnalysisDataMapping/index.tsx
packages/modules/src/networkAnalysisDataMapping/mappingTable.ts
packages/modules/src/networkAnalysisDataVis/index.tsx

It does actual data processing from reading files to calculating centrality measures. The code follows inputs/outputs specification of corresponding front end components. Later it will likely be replaced with kiara pipelines built with more fine grained modules.

Network analysis modules backend code

---

backend/jupyter-middleware/dharpa/vre/dev/modules/network_analysis.py
packages/data-mapping-table/src/TabularDataMappingForm.tsx
packages/data-mapping-table/src/TabularDataMappingRow.tsx
packages/modules/src/networkAnalysisDataMapping/index.tsx

Also convert mixed type columns to string in data mapping module.

Optional column names

---

backend/jupyter-middleware/setup.py

Because the latest kiara stopped working.

Pin kiara to a hash of version 0.0.1

---

applications/jupyter-app/README.md
applications/jupyter-app/package.json
applications/jupyter-app/src/electron/main.ts
applications/jupyter-app/src/server/scripts/install/macnix.sh
applications/jupyter-app/src/server/scripts/install/win.ps1
applications/jupyter-app/src/server/scripts/run/macnix.sh
applications/jupyter-app/src/server/scripts/run/win.ps1
applications/jupyter-app/webpack.config.electron.js

Updated scripts and electron main process file to check and update the version of the middleware.

Pin middleware version in electron app

---

applications/jupyter-app/electron-builder.yml
applications/jupyter-app/package.json
applications/jupyter-app/src/electron/components/appMenu.ts
applications/jupyter-app/src/electron/main.ts
applications/jupyter-app/src/electron/updater.ts
applications/jupyter-app/src/webapp/index.html
applications/jupyterlab-extension/package.json
yarn.lock

Checking updates of the electron app and allowing the user to download and install them via the main app menu.
Code in this PR has not been tested with real updates because a release needs to be published for it which can only be done once this code is in `master` branch. There might be amendments to this code after testing.
Also removes "copyright" from the app info window to fix https://github.com/DHARPA-Project/lumy-build/issues/3

Electron auto updater

---

applications/jupyter-app/package.json
applications/standalone/src/mock/context.ts
packages/client-core/src/hooks/useDataRepository.ts
packages/data-mapping-table/src/TabularDataMappingForm.tsx
packages/modules/src/dataSelection/DataSourceRow.tsx
packages/modules/src/dataSelection/index.tsx

To support changes in https://github.com/DHARPA-Project/lumy-middleware/pull/7

Data registry field renamed: alias -> label, middleware version bump.

---

applications/jupyter-app/package.json
applications/standalone/src/mock/resources/sampleLumyWorkflow.yml
packages/client-core/src/common/types/generated.ts
packages/client-core/src/common/types/index.ts
packages/client-ui/src/components/common/DataPreview.tsx
packages/client-ui/src/components/common/NoteEditor.tsx
packages/client-ui/src/components/common/WorkflowContainer.tsx
packages/client-ui/src/context/workflowContext.tsx
schema/json/types/workflow/LumyWorkflow.json

Using workflow layout metadata to understand what needs to be rendered.

Dynamic data preview

---

packages/client-ui/src/components/common/DataPreview.tsx
packages/client-ui/src/components/common/FeatureTabs.styles.ts
packages/client-ui/src/components/common/FeatureTabs.tsx
packages/client-ui/src/components/common/NoteEditor.styles.ts
packages/client-ui/src/components/common/NoteEditor.tsx
packages/client-ui/src/components/common/TabPanel.tsx
packages/client-ui/src/components/common/VerticalStepIndicator.styles.ts
packages/client-ui/src/components/common/WorkflowContainer.styles.ts
packages/client-ui/src/components/common/WorkflowContainer.tsx
packages/client-ui/src/components/common/WorkflowStep.styles.ts
packages/client-ui/src/components/common/code/CodeView.styles.ts
packages/client-ui/src/components/common/documentation/Documentation.tsx
packages/client-ui/src/components/common/navigation/LeftSideBarContainer.styles.ts
packages/client-ui/src/theme/index.ts
packages/client-ui/src/theme/muiDefaultTheme.ts
packages/client-ui/src/theme/muiThemeOverrides.ts
packages/modules/src/networkAnalysisDataVis/components/NetworkAnalysisVisualization.styles.ts
packages/notes-components/src/components/NoteItem.styles.ts
packages/notes-components/src/components/NoteItem.tsx
packages/notes-components/src/components/NoteItemsList.styles.ts
packages/notes-components/src/components/NoteItemsList.tsx

- Streamline theme generation
- Apply Roboto as default typeface
- Make MUI tabs look like tabs in Tropy
- Improve divider style
- Adjust graph container size to prevent unnecessary scroll bars
- Add placeholders when feature data missing
- ETC

Theme generation & style improvements

---

applications/jupyter-app/src/electron/components/appMenu.ts
yarn.lock

* added 'edit' menu which enables copy/paste hotkeys

Fix copy/paste in Electron app

---

packages/client-ui/src/components/App.tsx
packages/client-ui/src/components/common/SideDrawer.tsx
packages/client-ui/src/components/common/WorkflowLoadingProgressDialog.styles.ts
packages/client-ui/src/components/common/WorkflowLoadingProgressDialog.tsx
packages/client-ui/src/components/common/notifications/NotificationButton.styles.ts
packages/client-ui/src/components/common/notifications/NotificationButton.tsx
packages/client-ui/src/const/app.ts

use app top level element as the container for MUI Modal inherited components

MUI modals use app top level element

---

packages/client-core/src/common/mock.ts
packages/client-core/src/common/utils/index.ts
packages/client-core/src/common/utils/react.ts
packages/datavis-components/src/components/network-force.ts
packages/module-core/src/lumyComponent.tsx
packages/module-sandbox/src/backEndContext/sandbox/index.ts
packages/modules/src/hooks/useBoxSize.ts
packages/modules/src/networkAnalysisDataVis/components/NetworkAnalysisVisualization.styles.ts
packages/modules/src/networkAnalysisDataVis/components/NetworkAnalysisVisualization.tsx
packages/modules/src/networkAnalysisDataVis/context.tsx
packages/modules/src/networkAnalysisDataVis/mockProcessor.ts

- fixed mock processor access in a wrapped component
- a number of changes to network analysis module to improve performance

Mock Processor access and performance related fixes in network analysis module

---

applications/jupyter-app/package.json
yarn.lock

Fixes this bug: https://github.com/DHARPA-Project/lumy-middleware/pull/26

Middleware version bumped to 0.3.21
